#https://github.com/openstack/heat-templates/blob/master/hot/resource_group/server_with_volumes.yaml

heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
      
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini

  subnet_id:
    label: Sous-reseau
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: 22207ede-1911-47ca-b509-5698e34cf46c

resources:
  # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::ResourceGroup
  web_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          networks: 
            - network: reseau-pour-tous
          user_data: |
            #!/bin/bash
            wget http://secretaire.dorsal.polymtl.ca/~hdaoud/infonuagique/server.py
            python server.py &

  # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Neutron::Pool
  pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{get_resource: monitor}]
      subnet_id: {get_param: subnet_id}
      lb_method: ROUND_ROBIN # LEAST_CONNECTIONS, SOURCE_IP
      vip:
        protocol_port: 8000

# http://www.marcoberube.com/archives/335
  # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Neutron::LoadBalancer
  lbalancer:
    type: OS::Neutron::LoadBalancer
    properties:
      members: { get_attr: [web_nodes, refs] }
      pool_id: { get_resource: pool }
      protocol_port: 8000

  floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      fixed_ip_address: { get_attr: [pool, vip, address] }
      floating_network: ext-net
      port_id: { get_attr: [pool, vip, port_id] }

  # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Neutron::HealthMonitor
  monitor:
    type: OS::Neutron::HealthMonitor
    properties:	
      type: TCP
      delay: 13
      max_retries: 2
      timeout: 9


outputs:
  pool_ip_address:
    value: {get_attr: [pool, vip, address]}
    description: The IP address of the load balancing
  FloatingIP:
    description: Service public VIP
    value: { get_attr: [floatingip, floating_ip_address] }
  VIP:
    description: Internal VIP
    value: { get_attr: [pool, vip, address] }
